name: L3MEG-GH-TP1-essai
channels:
# channels priority
# see https://bioconda.github.io/
# conda-forge has highest prioriy
  - defaults
  - conda-forge
  - bioconda
  
dependencies:
  - jupyterlab>=3
  - nbresuse
  - python>=3.7
  - pip
  - nodejs
  - r-irkernel
  - r-base>=4.1.0
  - r-tidyverse 
  - merlin=1.1.2
  - pip:
    - bash_kernel
